# Generated by Django 4.2.15 on 2026-01-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('species', models.CharField(choices=[('dog', '狗'), ('cat', '貓'), ('other', '其他')], default='cat', max_length=10, verbose_name='種類')),
                ('gender', models.CharField(choices=[('M', '公'), ('F', '母'), ('U', '不詳')], default='U', max_length=1, verbose_name='性別')),
                ('breed', models.CharField(blank=True, max_length=80, null=True, verbose_name='品種')),
                ('pet_chip', models.CharField(blank=True, max_length=50, null=True, verbose_name='晶片')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('features', models.TextField(blank=True, null=True, verbose_name='特徵')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pets/avatars/', verbose_name='頭像')),
                ('is_neutered', models.BooleanField(default=False, verbose_name='是否結紮')),
                ('is_deceased', models.BooleanField(default=False, verbose_name='是否過世')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '寵物',
                'verbose_name_plural': '寵物',
                'ordering': ('-updated_at', '-id'),
            },
        ),
    ]
