# Generated by Django 4.2.15 on 2026-01-20 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目')),
                ('category', models.CharField(choices=[('eat', '飲食'), ('supplies', '用品'), ('medical', '醫療'), ('grooming', '美容'), ('transportation', '交通'), ('education', '教育'), ('entertainment', '娛樂'), ('travel', '旅遊'), ('other', '其他')], max_length=30, verbose_name='類別')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='pets.pets', verbose_name='寵物')),
            ],
            options={
                'verbose_name': '開支',
                'verbose_name_plural': '開支',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
