# Generated by Django 4.2.15 on 2026-01-20 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='日期')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='體重(公斤)')),
                ('water_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='飲水量(ml)')),
                ('food_g', models.PositiveIntegerField(blank=True, null=True, verbose_name='飼料量(克)')),
                ('supplements', models.CharField(blank=True, max_length=300, null=True, verbose_name='營養品(複選)')),
                ('mood', models.CharField(blank=True, choices=[('happy', '快樂'), ('calm', '平靜'), ('anxious', '焦慮'), ('angry', '生氣'), ('sad', '悲傷'), ('tired', '疲倦'), ('heat', '發情')], max_length=20, null=True, verbose_name='情緒')),
                ('poop_and_pee_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='上廁所次數')),
                ('poop_status', models.CharField(blank=True, choices=[('normal', '正常'), ('hard', '偏硬'), ('soft', '偏軟'), ('diarrhea', '稀便'), ('constipation', '無法排便')], max_length=20, null=True, verbose_name='排便狀況')),
                ('exercise_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='運動時間(分鐘)')),
                ('medications', models.CharField(blank=True, max_length=200, null=True, verbose_name='藥品')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='pets.pets', verbose_name='寵物')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['pet', 'recorded_at'], name='records_dai_pet_id_c7d755_idx')],
            },
        ),
    ]
