# Generated by Django 6.0.1 on 2026-01-21 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('type', models.CharField(choices=[('vaccine', '疫苗'), ('medical', '醫療 / 看診'), ('checkup', '定期健檢'), ('parasite', '驅蟲 / 寄生蟲'), ('grooming', '美容 / 洗牙'), ('training', '訓練'), ('travel', '旅遊 / 住宿'), ('social', '聚會'), ('birthday', '生日'), ('holiday', '節日'), ('other', '其他')], default='other', max_length=20, verbose_name='類型')),
                ('start_at', models.DateTimeField(verbose_name='開始時間')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('all_day', models.BooleanField(default=False, verbose_name='全天')),
                ('status', models.CharField(choices=[('planned', '未完成'), ('done', '已完成'), ('canceled', '已取消')], default='planned', max_length=20, verbose_name='狀態')),
                ('description', models.TextField(blank=True, default='', verbose_name='說明')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='提醒時間')),
                ('reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='已提醒時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pets', verbose_name='寵物')),
            ],
            options={
                'ordering': ['-start_at', '-id'],
                'indexes': [models.Index(fields=['pet', 'start_at'], name='planner_eve_pet_id_a6f527_idx'), models.Index(fields=['type', 'start_at'], name='planner_eve_type_43675e_idx'), models.Index(fields=['status', 'remind_at', 'reminded_at'], name='planner_eve_status_6b9955_idx')],
            },
        ),
    ]
